### ISSUE TITLE
Less confusing when no answers are available

### ISSUE THREAD

**Issue by pasky** [brmson/YodaQA-client#12]
When we have no answers (e.g. "Who directed the movie Frozen?"), the current situation is confusing as we show the single-answer list, with empty answer text. Let's special-case this situation and instead of answer list, show text like "No answers found, we are sorry.", maybe Google Search link?

**Comment by thePetrMarek** [comment]
I created "No answers found, we are sorry." message. I didn't added Google Search link, because we don't want to send our users to Google but rather let them try ask another question.
